Repository golfzaptw/action-auto-reviews-from-branches, pull requests merged in 2020-11, with the labels that each got.

#51 release 1.2.2 on develop
  package.json
Labels: status: WIP

#52 release 1.2.2 on master
  .github/workflows/danger.yml
  index.js
  package.json
  yarn.lock
Labels: status: WIP

#53 Use github.getOctokit() insted of github.GitHub() for @actions/github
  index.js
Labels: actions: bugfix, status: Done

#54 release 1.2.3 on develop
  package.json
Labels: status: Done

#55 release 1.2.3 on master
  .github/workflows/danger.yml
  index.js
  package.json
Labels: status: Done
